### PR TITLE
Upgrade highline gem

### PR DESCRIPTION
**Pull request by jtuttle**
Upgrades highline to fix a deprecation warning.

### CODE REVIEW

**Comment by jtuttle** [comment]
Upgrading the gem appears to make the deprecation warning go away without impairing functionality. I tested in the dev environment and confirmed that deprecation warning does appear on `main` but goes away when running w/ this branch. This is only testing an image built w/ Ruby 2.7 but I think that's okay for now.

**Review by imheresamir — APPROVED** [review]
LGTM, thanks!

**Comment by szamir1** [comment]
The Ruby CLI is not planned to be released. @jtuttle  are you aware of that?

**Comment by jtuttle** [comment]
@szamir1 Good catch, looks like we need to bump conjur-cli in the suite release. Automation didn't pick it up, possibly because the CHANGELOG is borked. Thanks.

**Comment by jtuttle** [comment]
@szamir1 Not sure what this is in reference to, the conjur-cli is one of the projects we are planning to release as part of the upcoming OSS Suite Release.

**Pull request merged**
