### PR TITLE
ERB security fix

### PR DESCRIPTION
**Pull request by dividedmind**
Currently `env:template` allows not only inspecting internal data structure but also full system access. This is not very problematic since templates are expected to come from and be used in a trusted environment, but it still allows doing some funny stuff either by accident or disgruntled malice.

This patch makes the templates run in a clean execution environment instead, with a $SAFE level of 3 to prevent dangerous OS calls.

We can also add a method_missing in the context to make it unnecessary to use the reduntant `conjurenv[]` with template variables.

(Actually why aren't we using some dead-simple template language instead, like `conjurenv.each {|k, v| template['{%s}' % k] = v}`?)

### CODE REVIEW

**Comment by inscitiv-ops-dev** [comment]
Can one of the admins verify this patch?

**Comment by jvanderhoof** [comment]
Closing this PR but keeping the branch available.

**Comment by dividedmind** [comment]
Why? I believe it's still valid.

**Comment by dividedmind** [comment]
Ah, ok, just saw the discussion on the internal slack.
Please provide context next time! For the record, @kgilpin said 
> Yes you can close it. Summon is the "right way" now.

I'm still not comfortable closing it given the command is not marked as deprecated (so far as I can tell). Also summon doesn't do template processing, so it's not exactly equivalent; not that I necessarily think template processing should be our business.

**Comment by dustinmm80** [comment]
Summon should support template processing. This has been my intent. The origins of summon are in `conjur env`, and that had template processing (ERB). I would like Summon to use Golang templates, because they're built into the stdlib, simple and lots of other popular Golang libs do this.

@dividedmind would you mind creating an issue for this in summon, if it doesn't already exist?

**Comment by dustinmm80** [comment]
This will be part of the biggest push to summon 'v2', along with rotation. This will probably be driven via secrets.yml. We'll start the XDD for this soon, after events probably.

**Comment by dividedmind** [comment]
@dustinmm80  https://github.com/cyberark/summon/issues/52 - we definitely need an XDD; since it's a public project, I believe we should make the XDD public too (with "anyone can comment") and link to it there.

**Pull request closed without merging**
